apiVersion: v2
name: common
description: A Library Helm Chart for grouping common logic
type: library
version: 1.3.0
appVersion: "1.3.0"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.4
