apiVersion: v2
name: tplchart
description: Templates to create components with commonly used values
type: library
version: 0.4.4
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.23.0
